### ISSUE TITLE
slash in tags

### ISSUE THREAD

**Issue by ahoy-jon** [miner/tagged#1]
What is the rationale behind slash in tags for records ? 

The default in Clojure seems to be without slash : 

``` clojure
(defrecord Yo [greet])

(pr-str (Yo. "yo"))
;=> "#user.Yo{:name \"yo\"}"
```

**Comment by miner** [comment]
EDN doesn't support Records.  The tagged project encodes Clojure Records into tagged data literals.  The slash is how EDN specifies a namespace qualified tag.
