### ISSUE TITLE
Doesn't play nicely with builtin datatypes

### ISSUE THREAD

**Issue by jjl** [miner/tagged#2]
I'm trying to serialise sorted maps such that they'll be automatically sorted on reading back in, so I created a printer for it which all works correctly.

Unfortunately it now looks for a function called clojure.lang/map->PersistentTreeMap which obviously doesn't exist. If I create it (and thus pollute the clojure.lang namespace), it works fine:

``` clojure
user=> (keys (edn/read-string {:default tag/tagged-default-reader} (print-str (sorted-map :a 1 :b 2))))
(:a :b)
```

Otherwise I get this:

``` clojure
user=> (keys (tag/read-string (print-str (sorted-map :a 1 :b 2))))
(:tag :value)
```

I'm not sure what the best way to deal with this is. We could perhaps have an override table as an optional argument?

**Comment by miner** [comment]
The tagged project is for handling Records as data-reader literals.  It sounds like you're using a custom print-method for sorted-maps (PersistentTreeMap) .  In general, I would not recommend writing custom print-methods for Clojure built-in types.  The rest of the world expects standard Clojure types printed the default way so it's asking for trouble to print things differently.  

In any case, you should use a tag that is in your namespace (not in clojure.lang), and implement a data-reader specifically for your tag.

Also, take a look at *print-dup*.  If you don't require EDN compatibility, that's probably the best way to get what you want from Clojure with respect to sorted-maps.
