### ISSUE TITLE
records with lowercase names are read as instances of tagged.TaggedValue

### ISSUE THREAD

**Issue by schmir** [miner/tagged#3]
I'm using records with lowercase names. When reading those records
back in, they are read as instances of tagged.TaggedValue instead of
the original record's type.

The problem seems to stem from the isUpperCase check in
https://github.com/miner/tagged/blob/master/src/miner/tagged.clj#L17

I'm not sure what's the purpose of that isUpperCase check. Can it be
removed?

Here's a short REPL session demonstrating the problem:

``` clojure
user> (require '[miner.tagged :as tag])
;; => nil
user> (defrecord rec [a])
;; => user.rec
user> (def r1 (->rec 1))
;; => #'user/r1
user> (defmethod print-method user.rec [this w] (tag/pr-tagged-record-on this w))
;; => #multifn[print-method 0x1c952c70]
user> (pr-str r1)
;; => "#user/rec {:a 1}"
user> (type (tag/read-string (pr-str r1)))
;; => miner.tagged.TaggedValue
```

**Comment by miner** [comment]
Capitalizing record names is the convention as it's convenient for Java interop.  The isUpperCase check is there mainly to be conservative about what the tagged-default-reader would do with unknown tags.

Yes, I think it could be removed.  It's unlikely that there would be an accidental collision with a user-defined function name "map->REC" where REC is the name of your record.  I'll give it a try.

In the meantime, the work-around would be to specify the reader explicitly.  For example,

```
(type (tag/read-string {:readers {'user/rec user/map->rec}} (pr-str r1)))
;; => user.rec
```

Admittedly, this is inconvenient.

**Comment by miner** [comment]
Version 0.4.1 has the isUpperCase check removed.  Please let me know if the new version works for you.

**Comment by schmir** [comment]
0.4.1 fixes the issue for me. Thank you very much!
